name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore packages
        run: |
          nuget restore
      - name: Build-windows
        run: |
          msbuild ShapesBalanceXamFormsApp/ShapesBalanceXamFormsApp.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
      - name: Build-Android
        run: |
          nuget restore
          msbuild ShapesBalanceXamFormsApp.Android/ShapesBalanceXamFormsApp.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
